In [58]:
import os
from PIL import Image

In [59]:
from face import Face
from face_package.face_detect import Detect
from face_package.face_emotion import Emotion
from face_package.face_matting import Matting
from face_package.face_recognition import Recognition
from face_package import DATA_DIR

In [60]:
import torch

torch.cuda.is_available()

True

In [61]:
detect_model = Detect()
matting_model = Matting()
emotion_model = Emotion()
recognition = Recognition()

face_handle = Face(detect_model, emotion_model, recognition, matting_model)


2024-12-30 22:46:16.630 | INFO     | face_package.face_detect:__init__:16 - model path is fd:\mse\code\face\face_package/../model/yolov11m-face.pt
2024-12-30 22:46:16.941 | INFO     | face_package.face_detect:__init__:21 - Loaded model, cuda is available


2024-12-30 22:46:17,747 - modelscope - WARNING - Model revision not specified, use revision: v2.0.2
2024-12-30 22:46:17,943 - modelscope - INFO - initiate model from C:\Users\67424\.cache\modelscope\hub\damo\cv_ir50_face-recognition_arcface
2024-12-30 22:46:17,943 - modelscope - INFO - initiate model from location C:\Users\67424\.cache\modelscope\hub\damo\cv_ir50_face-recognition_arcface.
2024-12-30 22:46:17,949 - modelscope - WARNING - No preprocessor field found in cfg.
2024-12-30 22:46:17,949 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-12-30 22:46:17,950 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\67424\\.cache\\modelscope\\hub\\damo\\cv_ir50_face-recognition_arcface'}. trying to build by task and model information.
2024-12-30 22:46:17,950 - modelscope - WARNING - Find task: face-recognition, model type: None. Insufficient in

2024-12-30 22:46:18,798 - modelscope - WARNING - Model revision not specified, use revision: v1.1
2024-12-30 22:46:19,016 - modelscope - INFO - initiate model from C:\Users\67424\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd
2024-12-30 22:46:19,017 - modelscope - INFO - initiate model from location C:\Users\67424\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd.
2024-12-30 22:46:19,018 - modelscope - INFO - initialize model from C:\Users\67424\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd
c:\Users\67424\.conda\envs\face\Lib\site-packages\mmdet\models\dense_heads\anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
c:\Users\67424\.conda\envs\face\Lib\site-packages\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "p

load checkpoint from local path: C:\Users\67424\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd\pytorch_model.pt


2024-12-30 22:46:19,688 - modelscope - INFO - face recognition model loaded!


In [62]:
person_image_dir = f"{DATA_DIR}/person"
group_image_dir = f"{DATA_DIR}/f5dff87ed6c3d3dcf1ed44ae36aa83e.jpg"

In [63]:
group_img = Image.open(group_image_dir)

In [64]:
face_handle.add_group_img(group_img)

2024-12-30 22:46:20.528 | INFO     | face_package.face_detect:detect_res:41 - [ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'face'}
obb: None
orig_img: array([[[236, 221, 205],
        [236, 221, 205],
        [236, 221, 205],
        ...,
        [239, 227, 215],
        [238, 226, 214],
        [237, 225, 213]],

       [[236, 221, 205],
        [236, 221, 205],
        [236, 221, 205],
        ...,
        [238, 226, 214],
        [237, 225, 213],
        [237, 225, 213]],

       [[236, 221, 205],
        [235, 220, 204],
        [235, 220, 204],
        ...,
        [237, 225, 213],
        [237, 225, 213],
        [237, 225, 213]],

       ...,

       [[194, 179, 176],
        [195, 183, 179],
        [198, 186, 182],
        ...,
        [216, 207, 204],
        [211, 199, 197],
        [209, 197, 195]],

       [[194, 180, 174],
        [195, 183, 177],
        [198, 186, 180],

In [65]:
person_dict ={}

In [66]:
for item in os.listdir(person_image_dir):
    name = os.path.basename(item)
    name = os.path.splitext(name)[0]
    path = f"{person_image_dir}/{item}"
    person_dict[name] = Image.open(path)

In [67]:
face_handle.add_person_img(person_dict)

2024-12-30 22:46:22.251 | INFO     | face:add_person_img:54 - decoder for 01巴昊
2024-12-30 22:46:22.271 | INFO     | face_package.face_detect:detect_res:41 - [ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'face'}
obb: None
orig_img: array([[[227,  84,   5],
        [228,  84,   5],
        [228,  84,   5],
        ...,
        [198,  67,   0],
        [216, 156, 124],
        [217, 217, 211]],

       [[227,  84,   5],
        [228,  84,   5],
        [228,  84,   5],
        ...,
        [198,  67,   0],
        [216, 156, 124],
        [217, 217, 211]],

       [[227,  83,   5],
        [227,  84,   5],
        [228,  84,   5],
        ...,
        [198,  67,   0],
        [216, 156, 124],
        [217, 217, 211]],

       ...,

       [[ 27,  20,  23],
        [ 26,  19,  22],
        [ 26,  19,  22],
        ...,
        [ 19,  12,  15],
        [134, 131, 131],
        [217, 217, 211

In [68]:
face_handle.person_img_info["01巴昊"]

array([[   0.032505,  -0.0019864,    0.046518,    0.051251,   -0.017292,   -0.026704,  -0.0027325,    0.041575,  -0.0054367,    0.022831,   0.0099905,    0.012185,    0.033611,   -0.034836, -0.00098056,   -0.033944,    0.042369,   -0.022597,    0.065202,    0.016136,   -0.025754,    0.069159,     -0.0148,
          -0.042195,    0.048734,    0.011652,    0.090958,    0.029178,    0.050415,   -0.069986,   -0.013688,   -0.015242,   -0.025829,    -0.03155,   0.0082051,     0.04706,   -0.086182,    0.011385,   -0.036018,    0.068639,  -0.0075006,   -0.082038,   -0.035773,   -0.051759,    0.044263,   0.0012695,
           0.010768,    0.074626,    -0.00593,   -0.028508,    0.088343,    0.054746,    0.032169,   0.0018406,    0.015218,    0.049307,     0.06116,   -0.048854,   -0.020901,   0.0089867,    0.089424,   -0.029586,    0.019574,   -0.015999,    -0.01786,   -0.039075,    0.045846,   -0.076621,    0.079953,
            0.10999,    0.017758,   -0.021603,    0.049055,   -0.019293,    0.0

In [69]:
face_handle.analysis()

2024-12-30 22:46:25.598 | INFO     | face:analysis:66 - person_candidate_dict is 65
2024-12-30 22:46:25.599 | INFO     | face:analysis:67 - unknow_group_face_dict is 64
2024-12-30 22:46:25.612 | INFO     | face:analysis:76 - score  0.7891231775283813, conf is 0.8
2024-12-30 22:46:25.612 | INFO     | face:analysis:89 - person_candidate_dict is 65
2024-12-30 22:46:25.613 | INFO     | face:analysis:90 - group_candidate_dict is 64
2024-12-30 22:46:25.614 | INFO     | face:analysis:91 - temp_unknow_group_face is 1
2024-12-30 22:46:25.627 | INFO     | face:analysis:76 - score  0.7329891920089722, conf is 0.8
2024-12-30 22:46:25.628 | INFO     | face:analysis:89 - person_candidate_dict is 65
2024-12-30 22:46:25.628 | INFO     | face:analysis:90 - group_candidate_dict is 64
2024-12-30 22:46:25.629 | INFO     | face:analysis:91 - temp_unknow_group_face is 2
2024-12-30 22:46:25.642 | INFO     | face:analysis:76 - score  0.5959715023636818, conf is 0.8
2024-12-30 22:46:25.642 | INFO     | face:an

In [70]:
face_handle.info["01巴昊"].keys()

dict_keys(['xywh', 'score'])

In [71]:
len(face_handle.info)

64

In [72]:
face_handle.info["郝学委"]

{'xywh': array([     5420.8,      3165.1,      308.29,       374.6]),
 'score': 0.5516356453299522}

In [73]:
import numpy as np

ys = np.zeros((len(face_handle.info), 1), dtype=np.float32)
hs = np.zeros((len(face_handle.info), 1), dtype=np.float32)  
for idx, item in  enumerate(face_handle.info):
    print(item)
    ys[int(idx)][0] = face_handle.info[item]["xywh"][1]
    hs[int(idx)][0] = face_handle.info[item]["xywh"][3]
    

55张广东
56周经京
11甘启昕
06丁九胜
47薛扬志
13韩永昆
32邵韦豪
21居佑泉
54詹洪
丁素芬
23李知锐
42吴洁
赵卫东
07董佐昌
46许丽瑄
刘钢
20靳英杰
09付宗菁
26卢琰
03曹彦龙
31任锐
30曲峥
58周艳华
35盛燕斐
41涂蝉永
33佘严
22李昀蔚
12高雨辰
48严成林
27麦巍瀚
28梅子豪
57周星
15胡闪兵
38陶兵军
51杨宇航
44徐大洪
01巴昊
10甘成武
14胡建
08杜健
34沈诚
45徐志毅
04陈毅敏
49杨锴
40田营航
39陶大令
53余盛龙
29潘缘
43肖晗
37孙超群
19蒋云豪
16黄立志
18黄正宇
52叶杨
02蔡觐阳
25刘骏逸
24刘建鹏
60朱英杰
36盛亦来
郝学委
59周毅
50杨汝坤
17黄一帆
廖炳华


In [74]:
from face_package.face_location import Location

location_model = Location(ys)

location_model.data

feature1  original_cluster  new_cluster
0   2457.658447                -1           -1
1   2782.758789                -1           -1
2   2295.309570                -1           -1
3   2484.052246                -1           -1
4   2820.346680                -1           -1
..          ...               ...          ...
59  3165.133789                -1           -1
60  3063.657227                -1           -1
61  2786.705566                -1           -1
62  3100.031250                -1           -1
63  2116.593994                -1           -1

[64 rows x 3 columns]

In [75]:
import pandas as pd
from sklearn.cluster import DBSCAN, KMeans

import numpy as np

xys = ys
me = np.mean(hs.reshape([-1]))
ds_model = DBSCAN(eps=me*0.4, min_samples=5)
model = KMeans(n_clusters=5)

labels = model.fit_predict( xys)
ds_labels = ds_model.fit_predict( xys)

# 获取核心样本的索引




In [76]:
me

356.3474

In [77]:
ds_labels

array([0, 1, 0, 0, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 0], dtype=int64)

In [78]:
labels

array([3, 4, 0, 3, 4, 2, 4, 1, 2, 1, 1, 1, 1, 4, 1, 1, 0, 1, 1, 3, 4, 0, 1, 1, 0, 0, 3, 3, 3, 2, 3, 3, 4, 0, 3, 0, 4, 0, 4, 0, 0, 3, 1, 0, 0, 0, 0, 0, 3, 0, 3, 3, 0, 0, 3, 0, 0, 0, 3, 1, 1, 4, 1, 0])

In [94]:
cluster_centers = model.cluster_centers_
cluster_centers

array([[     2154.3],
       [     3145.2],
       [     2722.3],
       [     2456.4],
       [     2798.2]], dtype=float32)

In [95]:
flat_arr = cluster_centers.flatten()
flat_arr


array([     2154.3,      3145.2,      2722.3,      2456.4,      2798.2], dtype=float32)

In [96]:
sorted_indices = np.argsort(flat_arr)
sorted_indices

array([0, 3, 2, 4, 1], dtype=int64)

In [97]:
cluster_centers[sorted_indices]

array([[     2154.3],
       [     2456.4],
       [     2722.3],
       [     2798.2],
       [     3145.2]], dtype=float32)

In [99]:
before_to_after = {i: sorted_indices[i] for i in range(len(flat_arr))}
before_to_after


{0: 0, 1: 3, 2: 2, 3: 4, 4: 1}

In [81]:

# 计算每个聚类的中心值

for cluster_id in np.unique(core_labels):
    if cluster_id!= -1:
        cluster_center = np.mean(core_samples[core_labels == cluster_id], axis=0)
        cluster_centers.append((cluster_id, cluster_center))

# 根据中心值的某个维度（这里假设第一个维度）从大到小排序
cluster_centers.sort(key=lambda x: x[1][0], reverse=True)

# 重新分配clusterid
new_cluster_ids = {old_id: new_id for new_id, (old_id, _) in enumerate(cluster_centers)}
new_labels = np.array([new_cluster_ids[label] if label!= -1 else -1 for label in labels])

# 将结果整理成DataFrame
data = pd.DataFrame(xys, columns=['feature1'])
data['original_cluster'] = labels
data['new_cluster'] = new_labels

KeyError: 3